download:
	wget https://artifacts.picoctf.net/c/8/wpa-ing_out.pcap
	wget https://github.com/zacheller/rockyou/raw/master/rockyou.txt.tar.gz

clean:
	rm wpa-ing_out.pcap rockyou.txt rockyou.txt.tar.gz
