download:
	wget https://jupiter.challenges.picoctf.org/static/a648ca6dd275b9454c5d0de6d0f6efd3/VaultDoor3.java

build:
	javac VaultDoor3-solution.java

clean:
	rm VaultDoor3.java
	rm VaultDoor3-solution.class

