download:
	wget https://mercury.picoctf.net/static/0bf545252b5120845e3b568b9ad0277e/ende.py
	wget https://mercury.picoctf.net/static/0bf545252b5120845e3b568b9ad0277e/pw.txt
	wget https://mercury.picoctf.net/static/0bf545252b5120845e3b568b9ad0277e/flag.txt.en

clean:
	rm ende.py
	rm pw.txt
	rm flag.txt.en
